name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run formatting check
      run: npm run format -- --check
      
    - name: Run tests
      run: npm test
      
    - name: Build all projects
      run: |
        # Test CLI functionality
        npx voc new test-project
        npx voc build test-project --prod
        npx voc list
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: build-artifacts
        path: |
          projects/*/dist/*.monolith.js
        retention-days: 7
        
  validate-js-only:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Verify no TypeScript files
      run: |
        # Ensure no .ts files exist (enforces pure JavaScript)
        if find . -name "*.ts" -not -path "./node_modules/*" | grep -q .; then
          echo "❌ TypeScript files found! This is a pure JavaScript environment."
          find . -name "*.ts" -not -path "./node_modules/*"
          exit 1
        else
          echo "✅ Pure JavaScript guarantee verified - no .ts files found"
        fi
        
    - name: Verify no TypeScript dependencies
      run: |
        # Check package.json files for TypeScript dependencies
        if grep -r "typescript\|@types/\|ts-" package.json core/package.json 2>/dev/null; then
          echo "❌ TypeScript dependencies found!"
          exit 1
        else
          echo "✅ No TypeScript dependencies found"
        fi